# Generated by Django 6.0.6 on 2026-07-08 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logic.ingredientcategory'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredientcategory',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='logic.mealcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(related_name='meal_ingredients', to='logic.ingredient'),
        ),
        migrations.AddField(
            model_name='meal',
            name='instructions',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='optional_ingredients',
            field=models.ManyToManyField(to='logic.ingredient'),
        ),
        migrations.AddField(
            model_name='mealcategory',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
