# Generated by Django 6.0.7 on 2026-07-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_alter_ingredient_name_alter_meal_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='optional_ingredients',
            field=models.ManyToManyField(null=True, to='logic.ingredient'),
        ),
    ]
