# Generated by Django 6.0.7 on 2026-07-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_alter_meal_optional_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='optional_ingredients',
            field=models.ManyToManyField(blank=True, to='logic.ingredient'),
        ),
    ]
